name: setup-hd
description: Setup hd, on GitHub Actions runners
inputs:
  version:
    description: Version of hd CLI to install
    required: false
    default: 0.0.69
runs:
  using: composite
  steps:
      # We verify the version against a SHA **in the published action itself**, not in the GCS bucket.
      - shell: bash
        run: |
          #!/bin/bash
          curl -L https://github.com/LinuxSuRen/http-downloader/releases/download/v${{ inputs.version }}/hd-linux-amd64.tar.gz | tar xzv hd
          sudo mv hd /usr/bin/hd
          hd fetch
