kind: Deployment
apiVersion: apps/v1
metadata:
  name: hd
  labels:
    app: hd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hd
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hd
    spec:
      containers:
        - name: hd
          image: 'ghcr.io/linuxsuren/hd:v0.0.60'
          command:
            - /bin/sh
          args:
            - '-c'
            - while true; do echo hello; sleep 10;done
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
